### ISSUE TITLE
Solution Guide for "Parsing Syslog for user behavior analysis" is missing

### ISSUE THREAD

**Issue by amtkhdkr** [fluent/fluentd-website#101]
From the page https://www.fluentd.org/guides
https://docs.fluentd.org/articles/parse-syslog this article is missing

![image](https://user-images.githubusercontent.com/6989784/84912335-f8b01280-b0d6-11ea-8181-6bcb2ff6cf30.png)

![image](https://user-images.githubusercontent.com/6989784/84912454-167d7780-b0d7-11ea-9bf8-7cf17cacf40d.png)

**Comment by repeatedly** [comment]
Thanks for the report! Just fixed.
