### ISSUE TITLE
Append 1 more case for case study section

### ISSUE THREAD

**Issue by toan-hf** [fluent/fluentd-website#102]
hello everyone 

As i saw our case study [here](https://github.com/fluent/fluentd-website/tree/master/content/casestudy) is apparently less resource than the huge successful cases in realistic which i heard. So i am thinking to write 1 more case especially inspired from what we have achieved with FluentD & FluentBit in last 5 months till now

Ideally, the article will cover for few parts like this blog post [here](https://engineering.hellofresh.com/logging-at-hf-10b090ef12e8)  already mentioned

Any objection with my idea ?

**Comment by toan-hf** [comment]
cc @repeatedly

**Comment by repeatedly** [comment]
No problem. If you can open a PR for adding article, we can review it :)

**Comment by toan-hf** [comment]
@repeatedly https://github.com/fluent/fluentd-website/pull/105

Thanks !

**Comment by kenhys** [comment]
Fixed via #105
