### ISSUE TITLE
Search field on fluentd.org does not working?

### ISSUE THREAD

**Issue by kenhys** [fluent/fluentd-website#122]
# The problem

![image](https://user-images.githubusercontent.com/225841/111751050-5c21d780-88d7-11eb-8837-b156a0fd41f3.png)

https://www.fluentd.org/ provides search button at right side of download button, but it does not work.

![image](https://user-images.githubusercontent.com/225841/121456247-bca94800-c9e0-11eb-865f-fc2cdc4bc1b9.png)

It seems that required resource is not found.

**Comment by kenhys** [comment]
It seems that it uses https://swiftype.com/documentation/site-search/autocomplete.

**Comment by kenhys** [comment]
It uses `fxqyKZ6ijDifm8yjw2an` as swifttype key.

**Comment by kenhys** [comment]
https://github.com/fluent/fluentd-website/blob/05b3d6b186d7c4c8b47f8b4f6977494bf1a17df5/views/layout.erb#L181-L193

**Comment by fujimotos** [comment]
TODO: Remove

**Comment by fujimotos** [comment]
Removed in 22a76ac5b136b70504ca8cd7e6db10549a23285f.
