### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mp3monster** [fluent/fluentd-website#138]
website page https://docs.fluentd.org/container-deployment/kubernetes contains the text:

Since applications runs in Pods and multiple Pods might exists across multiple nodes, we need a specific Fluentd-Pod that takes care of log collection on each node: Fluentd DaemonSet.

With the link to  https://github.com/fluent/fluentd-docs-gitbook/tree/da81ba70252eaa863cc28fc888584c59d6fc14d3/articles/fluentd_daemonset.md 

which doesnt exist

**Comment by agup006** [comment]
Thanks for reporting this issue is now fixed
