### ISSUE TITLE
Remove Redis or Replace Redis

### ISSUE THREAD

**Issue by toru-takahashi** [fluent/fluentd-website#232]
Hi Team,

I got the follwoing message from Heroku where the website is hosted.
It looks Redis that is used for the website will be removed.
I'm not sure a background why Redis is used.
Is it possible to remove Redis from the code or not?
If not, we need to migrate it to RDB or something

```
The Redis-To-Go team has chosen to discontinue their Heroku add-on as Redis-To-Go is in End of Life. The Redis-To-Go add-on will be removed from all Heroku apps on August 8, 2022. We advise you to remove the  Redis-To-Go add-on yourself before August 8, 2022 via the [Dashboard](https://hello.heroku.com/e/36622/2022-08-02/m3nh3n/1126629706?h=x0nnUveTv794j6YjANEnwF43r93mEjEzCGwkZqpJECw) or the [CLI](https://hello.heroku.com/e/36622/g-add-ons-destroying-an-add-on/m3nh3r/1126629706?h=x0nnUveTv794j6YjANEnwF43r93mEjEzCGwkZqpJECw).
For customers considering to moving to another Redis-as-a-Service provider, information on backups can be found here: https://hello.heroku.com/e/36622/documentation-heroku-backup/m3nh2g/1126629706?h=x0nnUveTv794j6YjANEnwF43r93mEjEzCGwkZqpJECw
```

**Comment by ashie** [comment]
Thanks for notifying it! We'll check it.

**Comment by ashie** [comment]
AFAIK it's used for storing plugins information: https://www.fluentd.org/plugins

**Comment by ashie** [comment]
I removed Redis dependent code in #233, generate JSON file instead.
Thanks for reporting it!

**Comment by toru-takahashi** [comment]
Thank you!

**Comment by ashie** [comment]
https://www.fluentd.org/plugins/all
Plugins data doesn't seem updated since committed plugins.json at 68947bc875e3908d779c543cf8d6e8cf820e6350.

We'll check this.
