### ISSUE TITLE
Fluentd.org site is listed as insecure

### ISSUE THREAD

**Issue by mjingle** [fluent/fluentd-website#250]
Since Jan 24, 2023, the fluentd.org website does not load when using a Chrome browser. Instead, a `Your connection is not private` warning appears and a `NET::ERR_CERT_COMMON_NAME_INVALID` error is listed.

**Comment by ashie** [comment]
Sorry for the inconvenience.
We are aware that and now working on recovery.
Please wait for a few days.

**Comment by ashie** [comment]
The web site has been recovered.
https://twitter.com/nora96o/status/1619127038451015681
