### ISSUE TITLE
SSL error SSL_ERROR_INTERNAL_ERROR_ALERT on the website

### ISSUE THREAD

**Issue by sagis-tikal** [fluent/fluentd-website#91]
When trying to access https://fluentd.org/ I receive the SSL error "SSL_ERROR_INTERNAL_ERROR_ALERT".
Browsing to http://fluentd.org/ or https://www.fluentd.org/ works.

**Comment by repeatedly** [comment]
You mean https://fluentd.org/ should be redirected to https://www.fluentd.org/ ?

**Comment by sagis-tikal** [comment]
I guess that's the most logical solution

**Comment by kenhys** [comment]
It seems that it was changed to redirect permanently.

```
% curl  https://fluentd.org 
<a href="https://www.fluentd.org">Moved Permanently</a>.
```
