### ISSUE TITLE
Link is Broken.

### ISSUE THREAD

**Issue by chandertechavidity** [fluent/fluentd-website#92]
https://github.com/fluent/fluentd-docs-gitbook/tree/5be966fbee2cde8c20955f7813354d86ed56b141/www.fluentd.org/architecture/README.md

**Comment by ganmacs** [comment]
Could you tell us which page you found the link is?

**Comment by chandertechavidity** [comment]
https://docs.fluentd.org/v/0.12/quickstart->  

Step 3: Learn More

Architecture Overview.

**Comment by ganmacs** [comment]
Thank you for the report. https://github.com/fluent/fluentd-docs-gitbook/pull/80 should fix this issue.

FYI: This repository is no longer used. If you find something to fix at https://docs.fluentd.org next time, please create an issue at https://github.com/fluent/fluentd-docs-gitbook. anyway, Thank you for your contribution!
